### ISSUE TITLE
Fail build with GTK3

### ISSUE THREAD

**Issue by sl1pkn07** [nonakap/xnp2#5]
complete log:

https://sl1pkn07.wtf/paste/view/0a9e0ad4

```
./configure \
    --prefix=/usr \
    --enable-ia32 \
    --enable-gtk3
```

gtk3 3.20.3

**Comment by nonakap** [comment]
Sorry, it is still incomplete in ver.0.86.

**Comment by sl1pkn07** [comment]
thanks

**Comment by qwIvan** [comment]
Do not consider supporting gtk3 in 0.86?
