### ISSUE TITLE
fail build with GCC 6.1.1

### ISSUE THREAD

**Issue by sl1pkn07** [nonakap/xnp2#6]
gcc versión 6.1.1 20160501 (GCC) 

log
https://sl1pkn07.wtf/paste/view/165465e3

greetings

**Comment by sl1pkn07** [comment]
patch from AUR by tegularius

https://aur.archlinux.org/cgit/aur.git/plain/patch.patch?h=xnp2

**Comment by nonakap** [comment]
I've applied the patch at svn repository.
please wait for next release.

**Comment by sl1pkn07** [comment]
with SVN you mean http://amethyst.yui.ne.jp/svn/pc98/np2/trunk/?

what is the difference between the code in SVN and in ths repository?
